import { REG_STRIP, LOG_LEVELS } from './constants.js';
import { ACTIONS } from './actions.js';

export const VSC_DEFAULTS = {
  audioBoolean: true,
  blacklist: ['www.instagram.com', '/^x.com/', 'imgur.com', 'teams.microsoft.com'].map((value) => value.replace(REG_STRIP, '')),
  controllerButtonSize: 14,
  controllerOpacity: 0.8,
  defaultLogLevel: LOG_LEVELS.INFO,
  displayKeyCode: 86, // key: V
  enabled: true,
  forceLastSavedSpeed: true,
  keyBindings: [
    { action: ACTIONS.display, force: false, code: 'KeyV', predefined: true },
    { action: ACTIONS.fast, force: false, code: 'KeyG', predefined: true },
    { action: ACTIONS.faster, force: true, code: 'BracketRight', predefined: true, shift: true },
    { action: ACTIONS.fixspeed_10, force: true, code: 'Digit1', predefined: false },
    { action: ACTIONS.fixspeed_15, force: true, code: 'Digit1', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_20, force: true, code: 'Digit2', predefined: false },
    { action: ACTIONS.fixspeed_25, force: true, code: 'Digit2', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_30, force: true, code: 'Digit3', predefined: false },
    { action: ACTIONS.fixspeed_35, force: true, code: 'Digit3', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_40, force: true, code: 'Digit4', predefined: false },
    { action: ACTIONS.fixspeed_45, force: true, code: 'Digit4', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_50, force: true, code: 'Digit5', predefined: false },
    { action: ACTIONS.fixspeed_55, force: true, code: 'Digit5', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_60, force: true, code: 'Digit6', predefined: false },
    { action: ACTIONS.fixspeed_65, force: true, code: 'Digit6', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_70, force: true, code: 'Digit7', predefined: false },
    { action: ACTIONS.fixspeed_75, force: true, code: 'Digit7', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_80, force: true, code: 'Digit8', predefined: false },
    { action: ACTIONS.fixspeed_85, force: true, code: 'Digit8', predefined: false, shift: true },
    { action: ACTIONS.fixspeed_90, force: true, code: 'Digit9', predefined: false },
    { action: ACTIONS.fixspeed_95, force: true, code: 'Digit9', predefined: false, shift: true },
    { action: ACTIONS.go_start, force: false, code: 'Digit0', predefined: false },
    { action: ACTIONS.pause, force: true, code: 'Period', predefined: false },
    { action: ACTIONS.pip_toggle, force: true, code: 'KeyP', predefined: false, shift: true, alt: true },
    { action: ACTIONS.reset, force: false, code: 'KeyR', predefined: true },
    { action: ACTIONS.slower, force: true, code: 'BracketLeft', predefined: true, shift: true },
    { action: ACTIONS.vol_down, force: true, code: 'ArrowDown', predefined: true },
    { action: ACTIONS.vol_up, force: true, code: 'ArrowUp', predefined: true },
    { action: ACTIONS.rewind, force: true, code: 'ArrowLeft', predefined: true },
    { action: ACTIONS.advance, force: true, code: 'ArrowRight', predefined: true },
  ],
  lastSpeed: 1.0,
  logLevel: LOG_LEVELS.WARNING,
  rememberSpeed: true,
  speed: 1.0,
  sources: {}, // empty object to hold stored values for each source
  startHidden: false,
};
